/**
 * @fileoverview Definitions for the Google Chrome Extensions™' APIs.
 * This document was generated by 'Get an Externs File of Google Chrome Extensions™' APIs for Closure Compiler™'
 * ( http://sites.google.com/site/mdeveloperk/en/googlechromeextensions/externchromeapis )
 * based on http://code.google.com/chrome/extensions/
 *
 * User Agent : Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534.24 (KHTML, like Gecko) Chrome/11.0.696.68 Safari/534.24
 * Time : Wed May 25 2011 08:21:41 GMT+0700 (N. Central Asia Daylight Time)
 * @externs
 */
var chrome = {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html */
chrome.bookmarks = {};


/** events of chrome.bookmarks */
/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onChanged */
chrome.bookmarks.onChanged;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onChildrenReordered */
chrome.bookmarks.onChildrenReordered;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onCreated */
chrome.bookmarks.onCreated;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onImportBegan */
chrome.bookmarks.onImportBegan;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onImportEnded */
chrome.bookmarks.onImportEnded;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onMoved */
chrome.bookmarks.onMoved;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#event-onRemoved */
chrome.bookmarks.onRemoved;


/** methods of chrome.bookmarks */
/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-create */
chrome.bookmarks.create = function(bookmark, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-get */
chrome.bookmarks.get = function(idOrIdList, callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-getChildren */
chrome.bookmarks.getChildren = function(id, callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-getRecent */
chrome.bookmarks.getRecent = function(numberOfItems, callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-getTree */
chrome.bookmarks.getTree = function(callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-move */
chrome.bookmarks.move = function(id, destination, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-remove */
chrome.bookmarks.remove = function(id, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-removeTree */
chrome.bookmarks.removeTree = function(id, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-search */
chrome.bookmarks.search = function(query, callback) {};


/** @see http://code.google.com/chrome/extensions/bookmarks.html#method-update */
chrome.bookmarks.update = function(id, changes, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/browserAction.html */
chrome.browserAction = {};


/** events of chrome.browserAction */
/** @see http://code.google.com/chrome/extensions/browserAction.html#event-onClicked */
chrome.browserAction.onClicked;


/** methods of chrome.browserAction */
/** @see http://code.google.com/chrome/extensions/browserAction.html#method-setBadgeBackgroundColor */
chrome.browserAction.setBadgeBackgroundColor = function(details) {};


/** @see http://code.google.com/chrome/extensions/browserAction.html#method-setBadgeText */
chrome.browserAction.setBadgeText = function(details) {};


/** @see http://code.google.com/chrome/extensions/browserAction.html#method-setIcon */
chrome.browserAction.setIcon = function(details) {};


/** @see http://code.google.com/chrome/extensions/browserAction.html#method-setPopup */
chrome.browserAction.setPopup = function(details) {};


/** @see http://code.google.com/chrome/extensions/browserAction.html#method-setTitle */
chrome.browserAction.setTitle = function(details) {};


/** @see http://code.google.com/chrome/extensions/contextMenus.html */
chrome.contextMenus = {};


/** methods of chrome.contextMenus */
/** @see http://code.google.com/chrome/extensions/contextMenus.html#method-create */
chrome.contextMenus.create = function(createProperties, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/contextMenus.html#method-remove */
chrome.contextMenus.remove = function(menuItemId, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/contextMenus.html#method-removeAll */
chrome.contextMenus.removeAll = function(opt_callback) {};


/** @see http://code.google.com/chrome/extensions/contextMenus.html#method-update */
chrome.contextMenus.update = function(id, updateProperties, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/cookies.html */
chrome.cookies = {};


/** events of chrome.cookies */
/** @see http://code.google.com/chrome/extensions/cookies.html#event-onChanged */
chrome.cookies.onChanged;


/** methods of chrome.cookies */
/** @see http://code.google.com/chrome/extensions/cookies.html#method-get */
chrome.cookies.get = function(details, callback) {};


/** @see http://code.google.com/chrome/extensions/cookies.html#method-getAll */
chrome.cookies.getAll = function(details, callback) {};


/** @see http://code.google.com/chrome/extensions/cookies.html#method-getAllCookieStores */
chrome.cookies.getAllCookieStores = function(callback) {};


/** @see http://code.google.com/chrome/extensions/cookies.html#method-remove */
chrome.cookies.remove = function(details, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/cookies.html#method-set */
chrome.cookies.set = function(details, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/extension.html */
chrome.extension = {};


/** properties of chrome.extension */
/** @see http://code.google.com/chrome/extensions/extension.html#property-lastError */
chrome.extension.lastError;


/** @see http://code.google.com/chrome/extensions/extension.html#property-inIncognitoContext */
chrome.extension.inIncognitoContext;


/** events of chrome.extension */
/** @see http://code.google.com/chrome/extensions/extension.html#event-onConnect */
chrome.extension.onConnect;


/** @see http://code.google.com/chrome/extensions/extension.html#event-onConnectExternal */
chrome.extension.onConnectExternal;


/** @see http://code.google.com/chrome/extensions/extension.html#event-onRequest */
chrome.extension.onRequest;


/** @see http://code.google.com/chrome/extensions/extension.html#event-onRequestExternal */
chrome.extension.onRequestExternal;


/** methods of chrome.extension */
/** @see http://code.google.com/chrome/extensions/extension.html#method-connect */
chrome.extension.connect = function(opt_extensionId, opt_connectInfo) {};


/** @see http://code.google.com/chrome/extensions/extension.html#method-getBackgroundPage */
chrome.extension.getBackgroundPage = function() {};


/** @see http://code.google.com/chrome/extensions/extension.html#method-getURL */
chrome.extension.getURL = function(path) {};


/** @see http://code.google.com/chrome/extensions/extension.html#method-getViews */
chrome.extension.getViews = function(opt_fetchProperties) {};


/** @see http://code.google.com/chrome/extensions/extension.html#method-sendRequest */
chrome.extension.sendRequest = function(opt_extensionId, request, opt_responseCallback) {};


/** @see http://code.google.com/chrome/extensions/extension.html#method-setUpdateUrlData */
chrome.extension.setUpdateUrlData = function(data) {};


/** @see http://code.google.com/chrome/extensions/history.html */
chrome.history = {};


/** events of chrome.history */
/** @see http://code.google.com/chrome/extensions/history.html#event-onVisitRemoved */
chrome.history.onVisitRemoved;


/** @see http://code.google.com/chrome/extensions/history.html#event-onVisited */
chrome.history.onVisited;


/** methods of chrome.history */
/** @see http://code.google.com/chrome/extensions/history.html#method-addUrl */
chrome.history.addUrl = function(details) {};


/** @see http://code.google.com/chrome/extensions/history.html#method-deleteAll */
chrome.history.deleteAll = function(callback) {};


/** @see http://code.google.com/chrome/extensions/history.html#method-deleteRange */
chrome.history.deleteRange = function(range, callback) {};


/** @see http://code.google.com/chrome/extensions/history.html#method-deleteUrl */
chrome.history.deleteUrl = function(details) {};


/** @see http://code.google.com/chrome/extensions/history.html#method-getVisits */
chrome.history.getVisits = function(details, callback) {};


/** @see http://code.google.com/chrome/extensions/history.html#method-search */
chrome.history.search = function(query, callback) {};


/** @see http://code.google.com/chrome/extensions/i18n.html */
chrome.i18n = {};


/** methods of chrome.i18n */
/** @see http://code.google.com/chrome/extensions/i18n.html#method-getAcceptLanguages */
chrome.i18n.getAcceptLanguages = function(callback) {};


/** @see http://code.google.com/chrome/extensions/i18n.html#method-getMessage */
chrome.i18n.getMessage = function(messageName, opt_substitutions) {};


/** @see http://code.google.com/chrome/extensions/idle.html */
chrome.idle = {};


/** events of chrome.idle */
/** @see http://code.google.com/chrome/extensions/idle.html#event-onStateChanged */
chrome.idle.onStateChanged;


/** methods of chrome.idle */
/** @see http://code.google.com/chrome/extensions/idle.html#method-queryState */
chrome.idle.queryState = function(thresholdSeconds, callback) {};


/** @see http://code.google.com/chrome/extensions/management.html */
chrome.management = {};


/** events of chrome.management */
/** @see http://code.google.com/chrome/extensions/management.html#event-onDisabled */
chrome.management.onDisabled;


/** @see http://code.google.com/chrome/extensions/management.html#event-onEnabled */
chrome.management.onEnabled;


/** @see http://code.google.com/chrome/extensions/management.html#event-onInstalled */
chrome.management.onInstalled;


/** @see http://code.google.com/chrome/extensions/management.html#event-onUninstalled */
chrome.management.onUninstalled;


/** methods of chrome.management */
/** @see http://code.google.com/chrome/extensions/management.html#method-get */
chrome.management.get = function(id, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/management.html#method-getAll */
chrome.management.getAll = function(opt_callback) {};


/** @see http://code.google.com/chrome/extensions/management.html#method-launchApp */
chrome.management.launchApp = function(id, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/management.html#method-setEnabled */
chrome.management.setEnabled = function(id, enabled, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/management.html#method-uninstall */
chrome.management.uninstall = function(id, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/omnibox.html */
chrome.omnibox = {};


/** events of chrome.omnibox */
/** @see http://code.google.com/chrome/extensions/omnibox.html#event-onInputCancelled */
chrome.omnibox.onInputCancelled;


/** @see http://code.google.com/chrome/extensions/omnibox.html#event-onInputChanged */
chrome.omnibox.onInputChanged;


/** @see http://code.google.com/chrome/extensions/omnibox.html#event-onInputEntered */
chrome.omnibox.onInputEntered;


/** @see http://code.google.com/chrome/extensions/omnibox.html#event-onInputStarted */
chrome.omnibox.onInputStarted;


/** methods of chrome.omnibox */
/** @see http://code.google.com/chrome/extensions/omnibox.html#method-setDefaultSuggestion */
chrome.omnibox.setDefaultSuggestion = function(suggestion) {};


/** @see http://code.google.com/chrome/extensions/pageAction.html */
chrome.pageAction = {};


/** events of chrome.pageAction */
/** @see http://code.google.com/chrome/extensions/pageAction.html#event-onClicked */
chrome.pageAction.onClicked;


/** methods of chrome.pageAction */
/** @see http://code.google.com/chrome/extensions/pageAction.html#method-hide */
chrome.pageAction.hide = function(tabId) {};


/** @see http://code.google.com/chrome/extensions/pageAction.html#method-setIcon */
chrome.pageAction.setIcon = function(details) {};


/** @see http://code.google.com/chrome/extensions/pageAction.html#method-setPopup */
chrome.pageAction.setPopup = function(details) {};


/** @see http://code.google.com/chrome/extensions/pageAction.html#method-setTitle */
chrome.pageAction.setTitle = function(details) {};


/** @see http://code.google.com/chrome/extensions/pageAction.html#method-show */
chrome.pageAction.show = function(tabId) {};


/** @see http://code.google.com/chrome/extensions/tabs.html */
chrome.tabs = {};


/** events of chrome.tabs */
/** @see http://code.google.com/chrome/extensions/tabs.html#event-onAttached */
chrome.tabs.onAttached;


/** @see http://code.google.com/chrome/extensions/tabs.html#event-onCreated */
chrome.tabs.onCreated;


/** @see http://code.google.com/chrome/extensions/tabs.html#event-onDetached */
chrome.tabs.onDetached;


/** @see http://code.google.com/chrome/extensions/tabs.html#event-onMoved */
chrome.tabs.onMoved;


/** @see http://code.google.com/chrome/extensions/tabs.html#event-onRemoved */
chrome.tabs.onRemoved;


/** @see http://code.google.com/chrome/extensions/tabs.html#event-onSelectionChanged */
chrome.tabs.onSelectionChanged;


/** @see http://code.google.com/chrome/extensions/tabs.html#event-onUpdated */
chrome.tabs.onUpdated;


/** methods of chrome.tabs */
/** @see http://code.google.com/chrome/extensions/tabs.html#method-captureVisibleTab */
chrome.tabs.captureVisibleTab = function(opt_windowId, opt_options, callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-connect */
chrome.tabs.connect = function(tabId, opt_connectInfo) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-create */
chrome.tabs.create = function(createProperties, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-detectLanguage */
chrome.tabs.detectLanguage = function(opt_tabId, callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-executeScript */
chrome.tabs.executeScript = function(opt_tabId, details, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-get */
chrome.tabs.get = function(tabId, callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-getAllInWindow */
chrome.tabs.getAllInWindow = function(opt_windowId, callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-getCurrent */
chrome.tabs.getCurrent = function(callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-getSelected */
chrome.tabs.getSelected = function(opt_windowId, callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-insertCSS */
chrome.tabs.insertCSS = function(opt_tabId, details, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-move */
chrome.tabs.move = function(tabId, moveProperties, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-remove */
chrome.tabs.remove = function(tabId, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-sendRequest */
chrome.tabs.sendRequest = function(tabId, request, opt_responseCallback) {};


/** @see http://code.google.com/chrome/extensions/tabs.html#method-update */
chrome.tabs.update = function(tabId, updateProperties, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html */
chrome.windows = {};


/** properties of chrome.windows */
/** @see http://code.google.com/chrome/extensions/windows.html#property-WINDOW_ID_NONE */
chrome.windows.WINDOW_ID_NONE;


/** events of chrome.windows */
/** @see http://code.google.com/chrome/extensions/windows.html#event-onCreated */
chrome.windows.onCreated;


/** @see http://code.google.com/chrome/extensions/windows.html#event-onFocusChanged */
chrome.windows.onFocusChanged;


/** @see http://code.google.com/chrome/extensions/windows.html#event-onRemoved */
chrome.windows.onRemoved;


/** methods of chrome.windows */
/** @see http://code.google.com/chrome/extensions/windows.html#method-create */
chrome.windows.create = function(opt_createData, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html#method-get */
chrome.windows.get = function(windowId, callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html#method-getAll */
chrome.windows.getAll = function(opt_getInfo, callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html#method-getCurrent */
chrome.windows.getCurrent = function(callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html#method-getLastFocused */
chrome.windows.getLastFocused = function(callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html#method-remove */
chrome.windows.remove = function(windowId, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/windows.html#method-update */
chrome.windows.update = function(windowId, updateInfo, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.clipboard.html */
chrome.experimental.clipboard = {};


/** methods of chrome.experimental.clipboard */
/** @see http://code.google.com/chrome/extensions/experimental.clipboard.html#method-executeCopy */
chrome.experimental.clipboard.executeCopy = function(tabId, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.clipboard.html#method-executeCut */
chrome.experimental.clipboard.executeCut = function(tabId, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.clipboard.html#method-executePaste */
chrome.experimental.clipboard.executePaste = function(tabId, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.contentSettings.misc.html */
chrome.experimental.contentSettings.misc = {};


/** properties of chrome.experimental.contentSettings.misc */
/** @see http://code.google.com/chrome/extensions/experimental.contentSettings.misc.html#property-blockThirdPartyCookies */
chrome.experimental.contentSettings.misc.blockThirdPartyCookies;


/** @see http://code.google.com/chrome/extensions/experimental.extension.html */
chrome.experimental.extension = {};


/** @see http://code.google.com/chrome/extensions/experimental.infobars.html */
chrome.experimental.infobars = {};


/** methods of chrome.experimental.infobars */
/** @see http://code.google.com/chrome/extensions/experimental.infobars.html#method-show */
chrome.experimental.infobars.show = function(details, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.processes.html */
chrome.experimental.processes = {};


/** events of chrome.experimental.processes */
/** @see http://code.google.com/chrome/extensions/experimental.processes.html#event-onUpdated */
chrome.experimental.processes.onUpdated;


/** methods of chrome.experimental.processes */
/** @see http://code.google.com/chrome/extensions/experimental.processes.html#method-getProcessIdForTab */
chrome.experimental.processes.getProcessIdForTab = function(tabId, callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.proxy.html */
chrome.experimental.proxy = {};


/** properties of chrome.experimental.proxy */
/** @see http://code.google.com/chrome/extensions/experimental.proxy.html#property-settings */
chrome.experimental.proxy.settings;


/** events of chrome.experimental.proxy */
/** @see http://code.google.com/chrome/extensions/experimental.proxy.html#event-onProxyError */
chrome.experimental.proxy.onProxyError;


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html */
chrome.experimental.sidebar = {};


/** events of chrome.experimental.sidebar */
/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#event-onStateChanged */
chrome.experimental.sidebar.onStateChanged;


/** methods of chrome.experimental.sidebar */
/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-collapse */
chrome.experimental.sidebar.collapse = function(opt_details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-expand */
chrome.experimental.sidebar.expand = function(opt_details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-getState */
chrome.experimental.sidebar.getState = function(opt_details, callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-hide */
chrome.experimental.sidebar.hide = function(opt_details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-navigate */
chrome.experimental.sidebar.navigate = function(details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-setBadgeText */
chrome.experimental.sidebar.setBadgeText = function(details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-setIcon */
chrome.experimental.sidebar.setIcon = function(details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-setTitle */
chrome.experimental.sidebar.setTitle = function(details) {};


/** @see http://code.google.com/chrome/extensions/experimental.sidebar.html#method-show */
chrome.experimental.sidebar.show = function(opt_details) {};


/** @see http://code.google.com/chrome/extensions/experimental.tts.html */
chrome.experimental.tts = {};


/** events of chrome.experimental.tts */
/** @see http://code.google.com/chrome/extensions/experimental.tts.html#event-onSpeak */
chrome.experimental.tts.onSpeak;


/** @see http://code.google.com/chrome/extensions/experimental.tts.html#event-onStop */
chrome.experimental.tts.onStop;


/** methods of chrome.experimental.tts */
/** @see http://code.google.com/chrome/extensions/experimental.tts.html#method-isSpeaking */
chrome.experimental.tts.isSpeaking = function(opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.tts.html#method-speak */
chrome.experimental.tts.speak = function(utterance, opt_options, opt_callback) {};


/** @see http://code.google.com/chrome/extensions/experimental.tts.html#method-stop */
chrome.experimental.tts.stop = function() {};


/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html */
chrome.experimental.webNavigation = {};


/** events of chrome.experimental.webNavigation */
/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html#event-onBeforeNavigate */
chrome.experimental.webNavigation.onBeforeNavigate;


/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html#event-onBeforeRetarget */
chrome.experimental.webNavigation.onBeforeRetarget;


/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html#event-onCommitted */
chrome.experimental.webNavigation.onCommitted;


/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html#event-onCompleted */
chrome.experimental.webNavigation.onCompleted;


/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html#event-onDOMContentLoaded */
chrome.experimental.webNavigation.onDOMContentLoaded;


/** @see http://code.google.com/chrome/extensions/experimental.webNavigation.html#event-onErrorOccurred */
chrome.experimental.webNavigation.onErrorOccurred;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html */
chrome.experimental.webRequest = {};


/** events of chrome.experimental.webRequest */
/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#event-onBeforeRedirect */
chrome.experimental.webRequest.onBeforeRedirect;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#event-onBeforeRequest */
chrome.experimental.webRequest.onBeforeRequest;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#event-onCompleted */
chrome.experimental.webRequest.onCompleted;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#event-onErrorOccurred */
chrome.experimental.webRequest.onErrorOccurred;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#event-onHeadersReceived */
chrome.experimental.webRequest.onHeadersReceived;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#event-onRequestSent */
chrome.experimental.webRequest.onRequestSent;


/** @see http://code.google.com/chrome/extensions/bookmarks.html#type-BookmarkTreeNode */
function BookmarkTreeNode() {}
BookmarkTreeNode.prototype.id;
BookmarkTreeNode.prototype.parentId;
BookmarkTreeNode.prototype.index;
BookmarkTreeNode.prototype.url;
BookmarkTreeNode.prototype.title;
BookmarkTreeNode.prototype.dateAdded;
BookmarkTreeNode.prototype.dateGroupModified;
BookmarkTreeNode.prototype.children;


/** @see http://code.google.com/chrome/extensions/contextMenus.html#type-OnClickData */
function OnClickData() {}
OnClickData.prototype.menuItemId;
OnClickData.prototype.parentMenuItemId;
OnClickData.prototype.mediaType;
OnClickData.prototype.linkUrl;
OnClickData.prototype.srcUrl;
OnClickData.prototype.pageUrl;
OnClickData.prototype.frameUrl;
OnClickData.prototype.selectionText;
OnClickData.prototype.editable;


/** @see http://code.google.com/chrome/extensions/cookies.html#type-Cookie */
function Cookie() {}
Cookie.prototype.name;
Cookie.prototype.value;
Cookie.prototype.domain;
Cookie.prototype.hostOnly;
Cookie.prototype.path;
Cookie.prototype.secure;
Cookie.prototype.httpOnly;
Cookie.prototype.session;
Cookie.prototype.expirationDate;
Cookie.prototype.storeId;


/** @see http://code.google.com/chrome/extensions/cookies.html#type-CookieStore */
function CookieStore() {}
CookieStore.prototype.id;
CookieStore.prototype.tabIds;


/** @see http://code.google.com/chrome/extensions/extension.html#type-MessageSender */
function MessageSender() {}
MessageSender.prototype.tab;
MessageSender.prototype.id;


/** @see http://code.google.com/chrome/extensions/extension.html#type-Event */
function Event() {}
Event.prototype.addListener = function() {};
Event.prototype.removeListener = function() {};
Event.prototype.hasListener = function() {};
Event.prototype.hasListeners = function() {};


/** @see http://code.google.com/chrome/extensions/extension.html#type-Port */
function Port() {}
Port.prototype.name;
Port.prototype.onDisconnect;
Port.prototype.onMessage;
Port.prototype.postMessage = function() {};
Port.prototype.sender;


/** @see http://code.google.com/chrome/extensions/history.html#type-HistoryItem */
function HistoryItem() {}
HistoryItem.prototype.id;
HistoryItem.prototype.url;
HistoryItem.prototype.title;
HistoryItem.prototype.lastVisitTime;
HistoryItem.prototype.visitCount;
HistoryItem.prototype.typedCount;


/** @see http://code.google.com/chrome/extensions/history.html#type-VisitItem */
function VisitItem() {}
VisitItem.prototype.id;
VisitItem.prototype.visitId;
VisitItem.prototype.visitTime;
VisitItem.prototype.referringVisitId;
VisitItem.prototype.transition;


/** @see http://code.google.com/chrome/extensions/management.html#type-IconInfo */
function IconInfo() {}
IconInfo.prototype.size;
IconInfo.prototype.url;


/** @see http://code.google.com/chrome/extensions/management.html#type-ExtensionInfo */
function ExtensionInfo() {}
ExtensionInfo.prototype.id;
ExtensionInfo.prototype.name;
ExtensionInfo.prototype.description;
ExtensionInfo.prototype.version;
ExtensionInfo.prototype.enabled;
ExtensionInfo.prototype.isApp;
ExtensionInfo.prototype.appLaunchUrl;
ExtensionInfo.prototype.homepageUrl;
ExtensionInfo.prototype.optionsUrl;
ExtensionInfo.prototype.icons;
ExtensionInfo.prototype.permissions;
ExtensionInfo.prototype.hostPermissions;


/** @see http://code.google.com/chrome/extensions/omnibox.html#type-SuggestResult */
function SuggestResult() {}
SuggestResult.prototype.content;
SuggestResult.prototype.description;


/** @see http://code.google.com/chrome/extensions/tabs.html#type-Tab */
function Tab() {}
Tab.prototype.id;
Tab.prototype.index;
Tab.prototype.windowId;
Tab.prototype.selected;
Tab.prototype.pinned;
Tab.prototype.url;


/** @see http://code.google.com/chrome/extensions/windows.html#type-Window */
function Window() {}
Window.prototype.id;
Window.prototype.focused;
Window.prototype.top;
Window.prototype.left;
Window.prototype.width;
Window.prototype.height;
Window.prototype.tabs;
Window.prototype.incognito;
Window.prototype.type;


/** @see http://code.google.com/chrome/extensions/experimental.extension.html#type-Preference */
function Preference() {}
Preference.prototype.incognito;
Preference.prototype.incognito;
Preference.prototype.value;
Preference.prototype.levelOfControl;
Preference.prototype.value;
Preference.prototype.incognito;


/** @see http://code.google.com/chrome/extensions/experimental.processes.html#type-Process */
function Process() {}
Process.prototype.id;
Process.prototype.type;
Process.prototype.cpu;
Process.prototype.network;
Process.prototype.privateMemory;
Process.prototype.sharedMemory;


/** @see http://code.google.com/chrome/extensions/experimental.proxy.html#type-ProxyServer */
function ProxyServer() {}
ProxyServer.prototype.scheme;
ProxyServer.prototype.host;
ProxyServer.prototype.port;


/** @see http://code.google.com/chrome/extensions/experimental.proxy.html#type-ProxyRules */
function ProxyRules() {}
ProxyRules.prototype.singleProxy;
ProxyRules.prototype.proxyForHttp;
ProxyRules.prototype.proxyForHttps;
ProxyRules.prototype.proxyForFtp;
ProxyRules.prototype.fallbackProxy;
ProxyRules.prototype.bypassList;


/** @see http://code.google.com/chrome/extensions/experimental.proxy.html#type-PacScript */
function PacScript() {}
PacScript.prototype.url;
PacScript.prototype.data;


/** @see http://code.google.com/chrome/extensions/experimental.proxy.html#type-ProxyConfig */
function ProxyConfig() {}
ProxyConfig.prototype.rules;
ProxyConfig.prototype.pacScript;
ProxyConfig.prototype.mode;


/** @see http://code.google.com/chrome/extensions/experimental.webRequest.html#type-RequestFilter */
function RequestFilter() {}
RequestFilter.prototype.urls;
RequestFilter.prototype.types;
RequestFilter.prototype.tabId;
RequestFilter.prototype.windowId;

